import json

state_abbreviations={
	'Vermont': 'VT',
	'Colorado': 'CO',
	'New Hampshire': 'NH',
	'Washington': 'WA',
	'Louisiana': 'LA',
	'Iowa': 'IA',
	'Georgia': 'GA',
	'Illinois': 'IL',
	'Maryland': 'MD',
	'Mississippi': 'MS',
	'Arkansas': 'AR',
	'Michigan': 'MI',
	'Pennsylvania': 'PA',
	'Maine': 'ME',
	'Montana': 'MT',
	'Wyoming': 'WY',
	'Nevada': 'NV',
	'Texas': 'TX',
	'New York': 'NY',
	'Massachusetts': 'MA',
	'Oregon': 'OR',
	'Kansas': 'KS',
	'Indiana': 'IN',
	'District of Columbia': 'DC',
	'Florida': 'FL',
	'West Virginia': 'WV',
	'New Jersey': 'NJ',
	'North Dakota': 'ND',
	'Wisconsin': 'WI',
	'Arizona': 'AZ',
	'Oklahoma': 'OK',
	'South Carolina': 'SC',
	'New Mexico': 'NM',
	'Tennessee': 'TN',
	'Hawaii': 'HI',
	'Delaware': 'DE',
	'Kentucky': 'KY',
	'Nebraska': 'NE',
	'Alabama': 'AL',
	'Rhode Island': 'RI',
	'South Dakota': 'SD',
	'Virginia': 'VA',
	'North Carolina': 'NC',
	'Minnesota': 'MN',
	'Missouri': 'MO',
	'Ohio': 'OH',
	'Connecticut': 'CT',
	'Idaho': 'ID',
	'Alaska': 'AK',
	'Utah': 'UT',
	'California': 'CA'
	}